version: '3.0'
services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "3001:3001"



    
